name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.18, 1.19, '1.20', 1.21]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
      - run: go mod download
      - run: go test ./...
